### ISSUE TITLE
Unauthorized; please provide valid token.

### ISSUE THREAD

**Issue by jjaomni** [canihavesomecoffee/theTVDbAPI#25]
[2021-10-12 00:02:56] NNTmux.ERROR: Unauthorized; please provide valid token. {"exception":"[object] (CanIHaveSomeCoffee\\TheTVDbAPI\\Exception\\UnauthorizedException(code: 0): Unauthorized; please provide valid token. at /var/www/NNTmux/vendor/canihavesomecoffee/thetvdbapi/src/Exception/UnauthorizedException.php:58)
[stacktrace]
#0 /var/www/NNTmux/vendor/canihavesomecoffee/thetvdbapi/src/TheTVDbAPI.php(284): CanIHaveSomeCoffee\\TheTVDbAPI\\Exception\\UnauthorizedException::invalidToken()
#1 /var/www/NNTmux/vendor/canihavesomecoffee/thetvdbapi/src/TheTVDbAPI.php(307): CanIHaveSomeCoffee\\TheTVDbAPI\\TheTVDbAPI->performAPICall()
#2 /var/www/NNTmux/vendor/canihavesomecoffee/thetvdbapi/src/Route/SeriesRoute.php(191): CanIHaveSomeCoffee\\TheTVDbAPI\\TheTVDbAPI->performAPICallWithJsonResponse()
#3 /var/www/NNTmux/Blacklight/processing/tv/TVDB.php(338): CanIHaveSomeCoffee\\TheTVDbAPI\\Route\\SeriesRoute->episodes()
#4 /var/www/NNTmux/Blacklight/processing/tv/TVDB.php(166): Blacklight\\processing\\tv\\TVDB->getEpisodeInfo()
#5 /var/www/NNTmux/Blacklight/processing/PostProcess.php(248): Blacklight\\processing\\tv\\TVDB->processSite()
#6 /var/www/NNTmux/Blacklight/Nfo.php(346): Blacklight\\processing\\PostProcess->processTv()
#7 /var/www/NNTmux/Blacklight/processing/PostProcess.php(217): Blacklight\\Nfo->processNfoFiles()
#8 /var/www/NNTmux/misc/update/postprocess.php(109): Blacklight\\processing\\PostProcess->processNfos()
#9 {main}
"} 

no clue why it's doing this.. i have a valid api4 key in the .env file

**Comment by canihavesomecoffee** [comment]
> ohhhh so i need to come up with funds then to get the shiney user pin??

Yes, they switched models for API v4 and newer. Now either the project pays (negotiable) for a project key, or each user pays for their separate key.
