### ISSUE TITLE
 Unable to use the "Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor" class as the "phpdocumentor/reflection-docblock" package is not installed

### ISSUE THREAD

**Issue by Fossil01** [canihavesomecoffee/theTVDbAPI#28]
This happens when I install my application in production without dev dependencies. `composer install --no-dev`

Looks like `phpdocumentor/reflection-docblock` is called by phpunit which is also in this repo's dev deps. So not sure why it throws an error in production.

```
[2022-02-12 14:07:42] REMOVED.ERROR: Unable to use the "Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor" class as the "phpdocumentor/reflection-docblock" package is not installed. {"exception":"[object] (LogicException(code: 0): Unable to use the \"Symfony\\Component\\PropertyInfo\\Extractor\\PhpDocExtractor\" class as the \"phpdocumentor/reflection-docblock\" package is not installed. at /var/www/REMOVED/vendor/symfony/property-info/Extractor/PhpDocExtractor.php:63)
[stacktrace]
#0 /var/www/REMOVED/vendor/canihavesomecoffee/thetvdbapi/src/DataParser.php(99): Symfony\\Component\\PropertyInfo\\Extractor\\PhpDocExtractor->__construct()
#1 /var/www/REMOVED/vendor/canihavesomecoffee/thetvdbapi/src/DataParser.php(68): CanIHaveSomeCoffee\\TheTVDbAPI\\DataParser::getSerializer()
#2 /var/www/REMOVED/vendor/canihavesomecoffee/thetvdbapi/src/DataParser.php(85): CanIHaveSomeCoffee\\TheTVDbAPI\\DataParser::parseData()
#3 /var/www/REMOVED/vendor/canihavesomecoffee/thetvdbapi/src/Route/SearchRoute.php(85): CanIHaveSomeCoffee\\TheTVDbAPI\\DataParser::parseDataArray()
#4 /var/www/REMOVED/Blacklight/processing/tv/TVDB.php(285): CanIHaveSomeCoffee\\TheTVDbAPI\\Route\\SearchRoute->search()
#5 /var/www/REMOVED/Blacklight/processing/tv/TVDB.php(148): Blacklight\\processing\\tv\\TVDB->getShowInfo()
#6 /var/www/REMOVED/Blacklight/processing/PostProcess.php(248): Blacklight\\processing\\tv\\TVDB->processSite()
#7 /var/www/REMOVED/misc/update/postprocess.php(125): Blacklight\\processing\\PostProcess->processTv()
#8 {main}
"}
```

**Comment by canihavesomecoffee** [comment]
Should be fixed in 2.1.2

It's indeed not installed, but I didn't stumble upon it because the default of composer seems to be to install dev dependencies too.
